install.packages("shiny")
install.packages("data.table")
install.packages("DT")
install.packages("magrittr")
install.packages("ggplot2")
install.packages("igraph")
install.packages("visNetwork")
install.packages("dplyr")
install.packages("tidyr")
install.packages("igraph")
install.packages("RColorBrewer")
install.packages("shinycssloaders")
install.packages("shinythemes")
install.packages("DT")

