install.packages("shiny")
install.packages("data.table")
install.packages("DT")
install.packages("magrittr")
install.packages("tidyverse")
install.packages("igraph")
install.packages("visNetwork")
install.packages("igraph")
install.packages("RColorBrewer")
install.packages("shinycssloaders")
install.packages("shinythemes")
install.packages("plotly")

